name: tests
run-name: tests
on:
  schedule:
    - cron: '30 11 * * *'

  workflow_call:

  push:
    branches:
      - "**"
jobs:
  smoke-tests:
    strategy:
      fail-fast: false
      matrix:
        image: [ 'ubuntu:focal', 'ubuntu:jammy', 'debian:latest', 'archlinux:latest' ]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
      env:
        TZ: Europe/Berlin
    steps:
    - name: 'Install git (Ubuntu, Debian)'
      if: ${{ contains(fromJSON('["ubuntu:focal", "ubuntu:jammy", "debian:latest"]'), matrix.image) }}
      run: apt-get update && apt-get install -y git
    - name: 'Install git (Arch)'
      if: ${{ contains('archlinux:latest', matrix.image) }}
      run: pacman -Syu --noconfirm git
    - name: 'Checkout repository'
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup timezone
      run: ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
    - name: 'Test (Ubuntu, Debian)'
      if: ${{ contains(fromJSON('["ubuntu:focal", "ubuntu:jammy", "debian:latest"]'), matrix.image) }}
      run:  bash setup.sh
    - name: 'Test (Arch)'
      if: ${{ contains('archlinux:latest', matrix.image) }}
      run: bash setup.sh
